name: Build Vite App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Create env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env

      - run: npm run build